package(default_visibility = ["//visibility:public"])
load("//:defs.bzl", "cc_lib")

cc_lib(
    name = "cli",
    hdrs = ["cli.h"],
    srcs = ["cli.cc"],
)

cc_lib(
    name = "signal",
    hdrs = ["signal.h"],
    srcs = ["signal.cc"],
)
