package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cli",
    hdrs = ["cli.h"],
    srcs = ["cli.cc"],
)

cc_library(
    name = "signal",
    hdrs = ["signal.h"],
    srcs = ["signal.cc"],
)
