package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cli",
    hdrs = ["cli.h"],
    srcs = ["cli.cc"],
    deps = [
        "//base:debug",
        "//base:meta",
        "@com_google_absl//absl/container:flat_hash_map",
    ],
)
