cc_test(
    name = "function_calls_test",
    srcs = ["function_calls_test.cc"],
    deps = [
        "//compiler",
        "//ir/interpretter:evaluate",
        "//test:module",
        "@com_google_googletest//:gtest_main",
    ],
)
