cc_test(
    name = "test",
    srcs = ["test.cc"],
    deps = [
        "//compiler",
        "//compiler:executable_module",
        "//diagnostic/consumer:aborting",
        "//frontend/source:string",
        "//interpretter:execute",
        "@com_google_googletest//:gtest_main",
    ],
)
