cc_binary(
    name = "icarus",
    srcs = ["main.cc"],
    deps = [
        "//ast:impl",
        "//backend:eval-impl",
        "//backend:exec-impl",
        "//frontend:lex-impl",
        "//frontend:parse",
        "//error:log-impl",
        "//init:cli-impl",
        "//init:signal-impl",
        "//ir:impl",
        "//misc:impl",
        "//property:property_map-impl",
        "//property:property_set-impl",
        "//property:property-impl",
        "//run:repl",
        "//run:compiler",
        "//type:impl",
    ],
)
