cc_binary(
    name = "icarus",
    srcs = ["main.cc"],
    deps = [
        "//ast:impl",
        "//backend:eval-impl",
        "//base/container:vector",
        "//frontend:lex",
        "//frontend:parse",
        "//error:log-impl",
        "//init:cli",
        "//init:signal",
        "//ir:impl",
        "//misc:impl",
        "//property:property_map-impl",
        "//run:repl",
        "//run:compiler",
        "//type:impl",
    ],
)
