bin/icarus programs/alloc_init.ic
bin/icarus programs/alloc_loop.ic
bin/icarus programs/alloc_loop2.ic
bin/icarus programs/array.ic
bin/icarus programs/array_lit.ic
bin/icarus programs/bool_assign.ic
bin/icarus programs/bool_test.ic
bin/icarus programs/bool_test_with_colon_eq.ic
bin/icarus programs/case.ic
bin/icarus programs/case_with_type_inference.ic
bin/icarus programs/cast.ic
bin/icarus programs/chain_test.ic
bin/icarus programs/char_array.ic
bin/icarus programs/code_gen_test.ic
bin/icarus programs/code_gen_test_with_type_inference.ic
bin/icarus programs/double_case.ic
bin/icarus programs/enum.ic
bin/icarus programs/fn_call.ic
bin/icarus programs/fn_expression_literal.ic
bin/icarus programs/if.ic
bin/icarus programs/import.ic
bin/icarus programs/import_cycle.ic
bin/icarus programs/infer_type.ic
bin/icarus programs/int_ops.ic
bin/icarus programs/is_digit.ic
bin/icarus programs/multidim_array.ic
bin/icarus programs/multiple_args.ic
bin/icarus programs/mutual_ptrs.ic
bin/icarus programs/mutual_ptrs2.ic
bin/icarus programs/negate.ic
bin/icarus programs/paren_test.ic
bin/icarus programs/pi.ic
bin/icarus programs/pointer.ic
bin/icarus programs/prime_loop.ic
bin/icarus programs/primes_recursive.ic
bin/icarus programs/print_array.ic
bin/icarus programs/print_test.ic
bin/icarus programs/squares.ic
bin/icarus programs/string_test.ic
bin/icarus programs/type.ic
bin/icarus programs/type_computation.ic
bin/icarus programs/type_return.ic
bin/icarus programs/type_literal.ic
bin/icarus programs/traits_test.ic
bin/icarus programs/uint_literal_test.ic
bin/icarus programs/void_return_test.ic
bin/icarus programs/water_state.ic
bin/icarus programs/while_break.ic
