#if not defined(IC_XMACRO_TOKEN_KIND)
#define IC_XMACRO_TOKEN_KIND(kind)
#endif  // not defined(IC_XMACRO_TOKEN_KIND)

#if not defined(IC_XMACRO_TOKEN_KIND_OPERATOR)
#define IC_XMACRO_TOKEN_KIND_OPERATOR(kind, symbol) IC_XMACRO_TOKEN_KIND(kind)
#endif  // not defined(IC_XMACRO_TOKEN_KIND_OPERATOR)

IC_XMACRO_TOKEN_KIND(Identifier)
IC_XMACRO_TOKEN_KIND(Integer)
IC_XMACRO_TOKEN_KIND(Newline)

IC_XMACRO_TOKEN_KIND_OPERATOR(ColonColonEqual, "::=")
IC_XMACRO_TOKEN_KIND_OPERATOR(ColonColon, "::")
IC_XMACRO_TOKEN_KIND_OPERATOR(ColonEqual, ":=")
IC_XMACRO_TOKEN_KIND_OPERATOR(Colon, ":")
IC_XMACRO_TOKEN_KIND_OPERATOR(Equal, "=")
IC_XMACRO_TOKEN_KIND_OPERATOR(EqualEqual, "==")

#undef IC_XMACRO_TOKEN_KIND
#undef IC_XMACRO_TOKEN_KIND_OPERATOR
