package(default_visibility = ["//visibility:public"])

cc_library(
    name = "builtin",
    hdrs = ["builtin.h"],
    srcs = ["builtin.cc"],
    deps = [
        "//base:debug",
        "//base:flyweight_map",
        "//core/type_system",
        "//ir/value:fn",
    ],
)
