package(default_visibility = ["//visibility:public"])

cc_library(
    name = "qual_type_iterator",
    hdrs = ["qual_type_iterator.h"],
    deps = [
        "//type:qual_type",
        "//type:type",
    ],
)
