package(default_visibility = ["//visibility:public"])

cc_library(
    name = "atoms",
    textual_hdrs = ["atoms.xmacro.h"],
    deps = [":primitive_types"],
)

cc_library(
    name = "primitive_types",
    textual_hdrs = ["primitive_types.xmacro.h"],
)

cc_library(
    name = "type_kind",
    textual_hdrs = ["type_kind.xmacro.h"],
)
