package(default_visibility = ["//visibility:public"])

cc_library(
    name = "bag",
    hdrs = ["bag.h"],
)

cc_library(
    name = "map",
    hdrs = ["map.h"],
)

cc_library(
    name = "tuple",
    hdrs = ["tuple.h"],
)

cc_library(
    name = "unordered_map",
    hdrs = ["unordered_map.h"],
    deps = ["//base:log"],
)

cc_library(
    name = "vector",
    hdrs = ["vector.h"],
)
