package(default_visibility = ["//visibility:public"])

cc_library(
    name = "jump",
    hdrs = ["jump.h"],
    deps = [
        "//base:stringify",
        "//base:util",
        "//core:fn_args",
        "//ir:reg",
        "//ir:results",
        "//type:typed_value",
    ],
)
