OP_MACRO(Death,                Death,               void,                    empty_)
OP_MACRO(Bytes,                Bytes,               type::Type const*,       type_arg_)
OP_MACRO(Align,                Align,               type::Type const*,       type_arg_)
OP_MACRO(NotBool,              Not,                 bool,                    reg_)
OP_MACRO(NotFlags,             Not,                 FlagsVal,                typed_reg_)
OP_MACRO(NegInt8,              Neg,                 int8_t,                  reg_)
OP_MACRO(NegInt16,             Neg,                 int16_t,                 reg_)
OP_MACRO(NegInt32,             Neg,                 int32_t,                 reg_)
OP_MACRO(NegInt64,             Neg,                 int64_t,                 reg_)
OP_MACRO(NegFloat32,           Neg,                 float,                   reg_)
OP_MACRO(NegFloat64,           Neg,                 double,                  reg_)
OP_MACRO(LoadBool,             Load,                bool,                    addr_arg_)
OP_MACRO(LoadInt8,             Load,                int8_t,                  addr_arg_)
OP_MACRO(LoadInt16,            Load,                int16_t,                 addr_arg_)
OP_MACRO(LoadInt32,            Load,                int32_t,                 addr_arg_)
OP_MACRO(LoadInt64,            Load,                int64_t,                 addr_arg_)
OP_MACRO(LoadNat8,             Load,                uint8_t,                 addr_arg_)
OP_MACRO(LoadNat16,            Load,                uint16_t,                addr_arg_)
OP_MACRO(LoadNat32,            Load,                uint32_t,                addr_arg_)
OP_MACRO(LoadNat64,            Load,                uint64_t,                addr_arg_)
OP_MACRO(LoadFloat32,          Load,                float,                   addr_arg_)
OP_MACRO(LoadFloat64,          Load,                double,                  addr_arg_)
OP_MACRO(LoadType,             Load,                type::Type const*,       addr_arg_)
OP_MACRO(LoadEnum,             Load,                EnumVal,                 addr_arg_)
OP_MACRO(LoadFlags,            Load,                FlagsVal,                addr_arg_)
OP_MACRO(LoadAddr,             Load,                ir::Addr,                addr_arg_)
OP_MACRO(LoadFunc,             Load,                AnyFunc,                 addr_arg_)
OP_MACRO(StoreBool,            Store,               bool,                    store_bool_)
OP_MACRO(StoreInt8,            Store,               int8_t,                  store_i8_)
OP_MACRO(StoreInt16,           Store,               int16_t,                 store_i16_)
OP_MACRO(StoreInt32,           Store,               int32_t,                 store_i32_)
OP_MACRO(StoreInt64,           Store,               int64_t,                 store_i64_)
OP_MACRO(StoreNat8,            Store,               uint8_t,                 store_u8_)
OP_MACRO(StoreNat16,           Store,               uint16_t,                store_u16_)
OP_MACRO(StoreNat32,           Store,               uint32_t,                store_u32_)
OP_MACRO(StoreNat64,           Store,               uint64_t,                store_u64_)
OP_MACRO(StoreFloat32,         Store,               float,                   store_float32_)
OP_MACRO(StoreFloat64,         Store,               double,                  store_float64_)
OP_MACRO(StoreType,            Store,               type::Type const*,       store_type_)
OP_MACRO(StoreEnum,            Store,               EnumVal,                 store_enum_)
OP_MACRO(StoreFunc,            Store,               ir::AnyFunc,             store_func_)
OP_MACRO(StoreFlags,           Store,               FlagsVal,                store_flags_)
OP_MACRO(StoreAddr,            Store,               ir::Addr,                store_addr_)
OP_MACRO(PrintType,            Print,               type::Type const*,       type_arg_)
OP_MACRO(PrintEnum,            Print,               EnumVal,                 print_enum_)
OP_MACRO(PrintFlags,           Print,               FlagsVal,                print_flags_)
OP_MACRO(PrintAddr,            Print,               ir::Addr,                addr_arg_)
OP_MACRO(XorFlags,             Xor,                 FlagsVal,                flags_args_)
OP_MACRO(OrFlags,              Or,                  FlagsVal,                flags_args_)
OP_MACRO(AndFlags,             And,                 FlagsVal,                flags_args_)
OP_MACRO(CreateStruct,         CreateStruct,        core::Scope const *,     create_struct_)
OP_MACRO(CreateStructField,    CreateStructField,   void,                    create_struct_field_)
OP_MACRO(SetStructFieldName,   SetStructFieldName,  void,                    set_struct_field_name_)
OP_MACRO(AddHashtagToField,    AddHashtagToField,   void,                    add_hashtag_)
OP_MACRO(AddHashtagToStruct,   AddHashtagToStruct,  void,                    add_hashtag_)
OP_MACRO(FinalizeStruct,       Finalize,            type::Struct const*,     reg_)
OP_MACRO(CreateEnum,           CreateEnum,          void,                    mod_)
OP_MACRO(AddEnumerator,        AddEnumerator,       void,                    add_enumerator_)
OP_MACRO(SetEnumerator,        SetEnumerator,       void,                    set_enumerator_)
OP_MACRO(FinalizeEnum,         FinalizeEnum,        void,                    reg_)
OP_MACRO(CreateFlags,          CreateFlags,         void,                    mod_)
OP_MACRO(AddFlag,              AddFlags,            void,                    add_enumerator_)
OP_MACRO(SetFlag,              SetFlags,            void,                    set_enumerator_)
OP_MACRO(FinalizeFlags,        FinalizeFlags,       void,                    reg_)
OP_MACRO(DebugIr,              DebugIr,             void,                    empty_)
OP_MACRO(Alloca,               Alloca,              type::Type const*,       type_)
OP_MACRO(PtrIncr,              PtrIncr,             void,                    ptr_incr_)
OP_MACRO(Field,                Field,               void,                    field_)
OP_MACRO(BufPtr,               BufPtr,              void,                    reg_)
OP_MACRO(Ptr,                  Ptr,                 void,                    reg_)
OP_MACRO(Arrow,                Arrow,               type::Type const*,       type_args_)
OP_MACRO(Array,                Array,               void,                    array_)
OP_MACRO(CreateTuple,          Create,              type::Tuple const*,      empty_)
OP_MACRO(AppendToTuple,        Append,              type::Tuple const*,      store_type_)
OP_MACRO(FinalizeTuple,        Finalize,            type::Tuple const*,      reg_)
OP_MACRO(CreateVariant,        Create,              type::Variant const*,    empty_)
OP_MACRO(AppendToVariant,      Append,              type::Variant const*,    store_type_)
OP_MACRO(FinalizeVariant,      Finalize,            type::Variant const*,    reg_)
OP_MACRO(CondJump,             Jump,                bool,                    cond_jump_)
OP_MACRO(UncondJump,           Jump,                void,                    block_index_)
OP_MACRO(ReturnJump,           Jump,                int32_t, /* any tag */   empty_)
OP_MACRO(JumpPlaceholder,      Jump,                void,                    block_def_)
OP_MACRO(VariantType,          VariantType,         void,                    addr_arg_)
OP_MACRO(VariantValue,         VariantValue,        void,                    addr_arg_)
OP_MACRO(Call,                 Call,                void,                    call_)
OP_MACRO(CastToInt8,           Cast,                int8_t,                  typed_reg_)
OP_MACRO(CastToNat8,           Cast,                uint8_t,                 typed_reg_)
OP_MACRO(CastToInt16,          Cast,                int16_t,                 typed_reg_)
OP_MACRO(CastToNat16,          Cast,                uint16_t,                typed_reg_)
OP_MACRO(CastToInt32,          Cast,                int32_t,                 typed_reg_)
OP_MACRO(CastToNat32,          Cast,                uint32_t,                typed_reg_)
OP_MACRO(CastToInt64,          Cast,                int64_t,                 typed_reg_)
OP_MACRO(CastToNat64,          Cast,                uint64_t,                typed_reg_)
OP_MACRO(CastToFloat32,        Cast,                float,                   typed_reg_)
OP_MACRO(CastToFloat64,        Cast,                double,                  typed_reg_)
OP_MACRO(CastToEnum,           Cast,                type::Enum const *,      reg_)
OP_MACRO(CastToFlags,          Cast,                type::Flags const *,     reg_)
OP_MACRO(CastPtr,              CastPtr,             type::Type const*,       typed_reg_)
OP_MACRO(PhiBool,              Phi,                 bool,                    phi_bool_)
OP_MACRO(PhiInt8,              Phi,                 int8_t,                  phi_i8_)
OP_MACRO(PhiInt16,             Phi,                 int16_t,                 phi_i16_)
OP_MACRO(PhiInt32,             Phi,                 int32_t,                 phi_i32_)
OP_MACRO(PhiInt64,             Phi,                 int64_t,                 phi_i64_)
OP_MACRO(PhiNat8,              Phi,                 uint8_t,                 phi_u8_)
OP_MACRO(PhiNat16,             Phi,                 uint16_t,                phi_u16_)
OP_MACRO(PhiNat32,             Phi,                 uint32_t,                phi_u32_)
OP_MACRO(PhiNat64,             Phi,                 uint64_t,                phi_u64_)
OP_MACRO(PhiFloat32,           Phi,                 float,                   phi_float32_)
OP_MACRO(PhiFloat64,           Phi,                 double,                  phi_float64_)
OP_MACRO(PhiType,              Phi,                 type::Type const*,       phi_type_)
OP_MACRO(PhiBlock,             Phi,                 BlockDef *,              phi_block_)
OP_MACRO(PhiAddr,              Phi,                 ir::Addr,                phi_addr_)
OP_MACRO(PhiEnum,              Phi,                 ir::EnumVal,             phi_enum_)
OP_MACRO(PhiFlags,             Phi,                 ir::FlagsVal,            phi_flags_)
OP_MACRO(PhiFunc,              Phi,                 ir::AnyFunc,             phi_func_)
OP_MACRO(GetRet,               GetRet,              void,                    get_ret_)
OP_MACRO(SetRetBool,           SetRet,              bool,                    set_ret_bool_)
OP_MACRO(SetRetInt8,           SetRet,              int8_t,                  set_ret_i8_)
OP_MACRO(SetRetInt16,          SetRet,              int16_t,                 set_ret_i16_)
OP_MACRO(SetRetInt32,          SetRet,              int32_t,                 set_ret_i32_)
OP_MACRO(SetRetInt64,          SetRet,              int64_t,                 set_ret_i64_)
OP_MACRO(SetRetNat8,           SetRet,              uint8_t,                 set_ret_u8_)
OP_MACRO(SetRetNat16,          SetRet,              uint16_t,                set_ret_u16_)
OP_MACRO(SetRetNat32,          SetRet,              uint32_t,                set_ret_u32_)
OP_MACRO(SetRetNat64,          SetRet,              uint64_t,                set_ret_u64_)
OP_MACRO(SetRetFloat32,        SetRet,              float,                   set_ret_float32_)
OP_MACRO(SetRetFloat64,        SetRet,              double,                  set_ret_float64_)
OP_MACRO(SetRetType,           SetRet,              type::Type const*,       set_ret_type_)
OP_MACRO(SetRetEnum,           SetRet,              EnumVal,                 set_ret_enum_)
OP_MACRO(SetRetFlags,          SetRet,              FlagsVal,                set_ret_flags_)
OP_MACRO(SetRetByteView,       SetRet,              std::string_view,        set_ret_byte_view_)
OP_MACRO(SetRetAddr,           SetRet,              ir::Addr,                set_ret_addr_)
OP_MACRO(SetRetFunc,           SetRet,              AnyFunc,                 set_ret_func_)
OP_MACRO(SetRetScope,          SetRet,              ir::ScopeDef*,           set_ret_scope_)
OP_MACRO(SetRetGeneric,        SetRet,              ast::FunctionLiteral  *, set_ret_generic_)
OP_MACRO(SetRetModule,         SetRet,              Module *,                set_ret_module_)
OP_MACRO(SetRetBlock,          SetRet,              BlockDef *,              set_ret_block_)
OP_MACRO(ArgumentCache,        ArgumentCache,       ast::StructLiteral *,    sl_)
OP_MACRO(NewOpaqueType,        NewOpaqueType,       void,                    reg_)
OP_MACRO(LoadSymbol,           LoadSymbol,          void,                    load_sym_)
OP_MACRO(Init,                 Init,                void,                    special1_)
OP_MACRO(Destroy,              Destroy,             void,                    special1_)
OP_MACRO(Move,                 Move,                void,                    special2_)
OP_MACRO(Copy,                 Copy,                void,                    special2_)
OP_MACRO(VerifyType,           VerifyType,          void,                    ast_)
OP_MACRO(EvaluateAsType,       EvaluateAsType,      type::Type const*,       ast_)
OP_MACRO(CreateContext,        CreateContext,       Context *,               mod_)
OP_MACRO(AddBoundConstant,     AddBoundConstant,    void,                    add_bc_)
OP_MACRO(DestroyContext,       DestroyContext,      void,                    reg_)
OP_MACRO(CreateScopeDef,       CreateScopeDef,      void,                    create_scope_def_)
OP_MACRO(AddScopeDefInit,      AddScopeDefInit,     void,                    add_scope_def_init_)
OP_MACRO(AddScopeDefDone,      AddScopeDefDone,     void,                    add_scope_def_done_)
OP_MACRO(FinishScopeDef,       FinishScopeDef,      void,                    empty_)
OP_MACRO(CreateBlockDef,       CreateBlockDef,      void,                    empty_)
OP_MACRO(FinishBlockDef,       FinishBlockDef,      void,                    byte_view_arg_)
OP_MACRO(AddBlockDefBefore,    AddBlockDefBefore,   void,                    any_fn_)
OP_MACRO(AddBlockDefAfter,     AddBlockDefAfter,    void,                    any_fn_)
