package(default_visibility = ["//serialization:__subpackages__"])

proto_library(
    name = "function_index",
    srcs = ["function_index.proto"],
)

proto_library(
    name = "module_map",
    srcs = ["module_map.proto"],
)

proto_library(
    name = "read_only_data",
    srcs = ["read_only_data.proto"],
)
