#ifndef ICARUS_AST_AST_H
#define ICARUS_AST_AST_H

#include "ast/access.h"
#include "ast/array_literal.h"
#include "ast/array_type.h"
#include "ast/binop.h"
#include "ast/block_literal.h"
#include "ast/block_node.h"
#include "ast/builtin_fn.h"
#include "ast/call.h"
#include "ast/cast.h"
#include "ast/chainop.h"
#include "ast/comma_list.h"
#include "ast/declaration.h"
#include "ast/dispatch_table.h"
#include "ast/enum_literal.h"
#include "ast/expression.h"
#include "ast/function_literal.h"
#include "ast/hashtag.h"
#include "ast/identifier.h"
#include "ast/import.h"
#include "ast/index.h"
#include "ast/interface.h"
#include "ast/match_declaration.h"
#include "ast/node.h"
#include "ast/overload_set.h"
#include "ast/repeated_unop.h"
#include "ast/scope_literal.h"
#include "ast/scope_node.h"
#include "ast/statements.h"
#include "ast/struct_literal.h"
#include "ast/struct_type.h"
#include "ast/switch.h"
#include "ast/terminal.h"
#include "ast/unop.h"

#endif  // ICARUS_AST_AST_H
