#if not defined(IC_XMACRO_PARSER_STATE)
#error `IC_XMACRO_PARSER_STATE` must be defined.
#endif

IC_XMACRO_PARSER_STATE(Newlines)

IC_XMACRO_PARSER_STATE(Module)

IC_XMACRO_PARSER_STATE(Statement)
IC_XMACRO_PARSER_STATE(StatementSequence)
IC_XMACRO_PARSER_STATE(ResolveStatementSequence)
IC_XMACRO_PARSER_STATE(SubsequentStatementSequence)

IC_XMACRO_PARSER_STATE(InvocationArgumentSequence)
IC_XMACRO_PARSER_STATE(ResolveInvocationArgumentSequence)

IC_XMACRO_PARSER_STATE(Declaration)
IC_XMACRO_PARSER_STATE(DeclaredSymbol)
IC_XMACRO_PARSER_STATE(ResolveInferredTypeDeclaration)
IC_XMACRO_PARSER_STATE(ResolveUninferredTypeDeclaration)
IC_XMACRO_PARSER_STATE(ResolveDefaultedDeclaration)

IC_XMACRO_PARSER_STATE(Expression)
IC_XMACRO_PARSER_STATE(ExpressionSuffix)
IC_XMACRO_PARSER_STATE(ResolveMemberTerm)
IC_XMACRO_PARSER_STATE(AtomicTerm)

IC_XMACRO_PARSER_STATE(ResolveUnaryExpression)
IC_XMACRO_PARSER_STATE(ResolveImport)

IC_XMACRO_PARSER_STATE(ResolveExpressionGroup)
IC_XMACRO_PARSER_STATE(ExpressionClosing)

#undef IC_XMACRO_PARSER_STATE
#undef IC_XMACRO_PARSER_STATE_SEQUENCE
