#if not defined(IC_XMACRO_PRECEDENCE_GROUP)
#error `IC_XMACRO_PRECEDENCE_GROUP` must be defined.
#endif

IC_XMACRO_PRECEDENCE_GROUP(Loosest)
IC_XMACRO_PRECEDENCE_GROUP(Function)
IC_XMACRO_PRECEDENCE_GROUP(Comparison)
IC_XMACRO_PRECEDENCE_GROUP(PlusMinus)
IC_XMACRO_PRECEDENCE_GROUP(Modulus)
IC_XMACRO_PRECEDENCE_GROUP(MultiplyDivide)

#undef IC_XMACRO_PRECEDENCE_GROUP
