PRIMITIVE_MACRO(Bool, Bool, bool)
PRIMITIVE_MACRO(Char, Char, char)
PRIMITIVE_MACRO(Code, Code, code)
PRIMITIVE_MACRO(Int, Int, int)
PRIMITIVE_MACRO(Real, Real, real)
PRIMITIVE_MACRO(Type_, Type, type)
PRIMITIVE_MACRO(NullPtr, NullPtr, null - pointer)
PRIMITIVE_MACRO(EmptyArray, EmptyArray, empty - array)
PRIMITIVE_MACRO(Err, Err, err)
PRIMITIVE_MACRO(Generic, Generic, generic)
PRIMITIVE_MACRO(OptBlock,   OptBlock,   block?)
PRIMITIVE_MACRO(Block, Block, block)
PRIMITIVE_MACRO(Module, Module, module)
PRIMITIVE_MACRO(Interface, Interface, interface)
