package(default_visibility = ["//visibility:public"])
load("//:defs.bzl", "cc_lib")

# Directory of things I haven't totally figured out how to organize yet.

cc_lib(
    name = "combine_blocks",
    deps = [
        "//base:log",
        "//ir:compiled_fn",
    ],
    test_deps = None,
)
