package(default_visibility = ["//toolchain/stdlib/compat/c:__subpackages__"])

cc_binary(
    name = "c_types_generator",
    srcs = ["c_types_generator.cc"],
)

cc_binary(
    name = "generate",
    srcs = ["generate.cc"],
)

cc_binary(
    name = "generate_c_values",
    srcs = ["generate_c_values.cc"],
)
