package(default_visibility = ["//visibility:private"])

load("//toolchain:ic_rule.bzl", "ic_library")

ic_library(
    name = "types",
    srcs = ["types.ic"],
    visibility = ["//visibility:public"],
)

ic_library(
    name = "errno",
    srcs = ["errno.ic"],
    visibility = ["//visibility:public"],
)
