load("//toolchain:ic_rule.bzl", "ic_low_level_library")

ic_low_level_library(
    name = "ctype",
    visibility = ["//visibility:public"],
    srcs = ["ctype.ic"],
    deps = [":types"],
)

ic_low_level_library(
    name = "math",
    visibility = ["//visibility:public"],
    srcs = ["math.ic"],
    deps = [":types"],
)

ic_low_level_library(
    name = "stdlib",
    visibility = ["//visibility:public"],
    srcs = ["stdlib.ic"],
    deps = [":types"],
)

ic_low_level_library(
    name = "stdio",
    visibility = ["//visibility:public"],
    srcs = ["stdio.ic"],
    deps = [":types"],
)

ic_low_level_library(
    name = "string",
    visibility = ["//visibility:public"],
    srcs = ["string.ic"],
    deps = [":types"],
)

ic_low_level_library(
    name = "types",
    visibility = ["//visibility:public"],
    srcs = ["types.ic"],
)
