name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      ICARUS_MODULE_PATH: stdlib
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-cache
      - name: Test
        run: >-
          bazel test -- ...
