name: CI
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      ICARUS_MODULE_PATH: stdlib
    steps:
      - name: Setup bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: >-
          bazel test --
          ast/... base/... compiler/verify/... compiler/emit/... core/...
          diagnostic/... frontend/... ir/... module/... opt/... type/...
      - name: Smoke Tests
        run: "./examples/smoke_test.sh"
