name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 16
          platform: x64
      - name: Test Debug Build
        run: >-
          bazel test -c dbg ...
      - name: Test ASAN Build
        run: >-
          bazel test --config=asan ...
      - name: Test Optimized Build
        run: >-
          bazel test -c opt ...
