name: CI
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ICARUS_MODULE_PATH: stdlib
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        env:
          version: 4.2.1
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-{{ env.version }}-bazel-cache
      - name: Test
        run: >-
          bazel test --
          ast/... base/... compiler/verify/... compiler/emit/... core/...
          diagnostic/... frontend/... ir/... module/... type/...
      - name: Smoke Tests
        run: "./examples/smoke_test.sh"
